trigger:
  branches:
    include:
    - main
  tags:
    include:
    - v*
    - refs/tags/v*

pr:
  branches:
    include:
    - main

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'

pool:
  vmImage: $(imageName)

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- bash: |
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    echo ">>> Started xvfb"
  displayName: Start xvfb
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

- bash: |
    echo ">>> Run npm install and Compile vscode-test"
    npm install && npm run compile
    echo ">>> Run sample integration test"
    npm install && npm run compile && npm run tests
  displayName: Run Tests
  env:
    DISPLAY: ':99.0'

- bash: |
    echo ">>> Publish"
    npm run deploy
    displayName: Publish
    condition: add(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'), eq(variables['Agent.OS'], 'Linux'))
    env:
      VSCE_PAT: $(VSCE_PAT)